config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  get 'static_pages/404', :to => 'static_pages#404'
  resources :searches, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def create
    @client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV["CONSUMER_KEY"]
      config.consumer_secret     = ENV["CONSUMER_SECRET"]
      config.access_token        = ENV["ACCESS_TOKEN"]
      config.access_token_secret = ENV["ACCESS_TOKEN_SECRET"]
    end
    @search = (params[:search][:username])
    begin
      @tweets = @client.user_timeline("#{@search}",{count: 25})
    rescue
      redirect_to static_pages_404_url
      return
    end
    render 'static_pages/index'
  end

  private
  def search_params
    params.require(:search).permit(:username)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweets Grabber</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => 'image/png'%>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/static_pages/404.html.erb
<h1>That username is private or does not exist. Please try again</h1>

<a href="/">
  <div id="index-link">
    Back To Index
  </div>
</a>

app/views/static_pages/index.html.erb
<h1>Tweets Display</h1>

<h3>Find The Latest Tweets from Your Favorite Users!</h3>

<form action="<%= searches_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <div id="input">
    <label>Twitter Handle
      <img src="/assets/twitter.png" alt="">
      <input type="text" name="search[username]" value="" placeholder="@dan_abramov" required>
    </label>
  </div>
  <input type="submit" value="Search">
</form>
<% if @tweets %>
  <h1>
    <%= sanitize @search %>'s Tweets!
  </h1>
  <div id="tweet-container">
    <% @tweets.each do |tweet| %>
    <div class="tweet-box" data-url="<%=tweet.uri%>">
      <h3>
        <%= tweet.full_text %>
      </h3>
      </div>
    <% end %>
  </div>
<% end %>